# Generated by Django 3.1.7 on 2021-03-21 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный номер абонента')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО абонента')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='текущий баланс на счете')),
                ('hold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='холды на счете')),
                ('status', models.CharField(choices=[('ON', 'Открыт'), ('OFF', 'Закрыт')], default='ON', max_length=3, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
    ]
